"""add payment_method to orders

Revision ID: db7089fec8db
Revises: aebbe3533f0c
Create Date: 2025-05-17 15:10:13.613864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7089fec8db'
down_revision: Union[str, None] = 'aebbe3533f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Bước 1: Cho phép nullable tạm thời để tránh lỗi khi có dữ liệu cũ
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))

    # Bước 2: Gán giá trị mặc định ('cod') cho tất cả các dòng cũ
    op.execute("UPDATE orders SET payment_method = 'cod' WHERE payment_method IS NULL")

    # Bước 3: Bây giờ mới set lại nullable=False để giữ schema chặt chẽ
    op.alter_column('orders', 'payment_method', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
